urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('htmlmail.views',
    url(r'^$', 'home', name='home'),
    url(r'^preview/(?P<pk>\d+)$', 'preview', name='preview'),
)

urlpatterns += patterns('',
    # url(r'^htmlmail/', include('htmlmail.foo.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

htmlmail/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import threading
from django.db import models
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from mailer.engine import send_all

class Tmail(models.Model):
    title = models.CharField('邮件标题',max_length=60)
    reply = models.EmailField('回复到')
    tname  = models.CharField('模板名称',max_length=30)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title or self.tname

    def tpath(self):
        return 'mail/%s.html' % self.tname

    def html_content(self):
        return render_to_string(self.tpath())

    def text_content(self):
        return 'TODO'

class Mailer(threading.Thread):

    def run(self):
        print 'send all in thread begin...'
        send_all()
        print 'send all in thread done...'

class Send(models.Model):
    tmail = models.ForeignKey(Tmail,verbose_name='邮件模板')
    title = models.CharField('邮件标题',max_length=60)
    reply = models.EmailField('回复到')
    tname  = models.CharField('模板名称',max_length=30)
    mails = models.TextField('收件人',max_length=2048,blank=True)
    status = models.CharField('状态',max_length=10,default='todo')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    def save(self,*args,**kwargs):
        if not self.pk:
            # info backup
            self.title = self.tmail.title
            self.reply = self.tmail.reply
            self.tname = self.tmail.tname
        super(Send,self).save(*args,**kwargs)

    def do(self):
        from_email = settings.EMAIL_HOST_USER
        tmail = self.tmail
        total = 0
        success = 0
        for mail in self.mails.split(','):
            total += 1
            try:
                msg = EmailMultiAlternatives(
                        tmail.title,
                        tmail.text_content(),
                        from_email,
                        [mail],
                        #headers = {'Reply-To': tmail.reply}
                    )
                msg.attach_alternative(tmail.html_content(), "text/html")
                print 'sending mail to %s' % mail
                msg.send()
                success += 1
            except:
                print 'sending fail: %s' % mail
                continue
        self.status = 'done'
        self.save()
        if settings.EMAIL_SEND_NOW:
            mailer = Mailer()
            mailer.start()
        return total,success

htmlmail/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re
from django import forms
from .models import Send


class SendForm(forms.ModelForm):
    class Meta:
        model = Send
        fields = ('tmail','mails')

    def clean_mails(self):
        text = self.cleaned_data['mails']
        r = re.compile(r'([\w\-\.]+@(\w[\w\-]+\.)+[\w\-]+)')
        matches = r.findall(text)
        mails = set([])
        for match in matches:
            m = match[0]
            if m not in mails:
                mails.add(m)
                print 'match mail:',m
            else:
                print 'skip repteated mail:',m
        return ','.join(mails)

htmlmail/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
#from django.contrib.auth.models import User
from django.contrib import messages
from forms import SendForm
from . import models as m

import os
APP_NAME = os.path.split(os.path.dirname(__file__))[-1]


def home(request):
    if request.method == 'GET':
        initial={
            'mails':'guoqiao@insigma.com.cn,guoqiao@gmail.com,pengxinwei@insigma.com.cn',
            'tmail':1,
        }
        form = SendForm(initial=initial)
    else:
        form = SendForm(request.POST)
        if form.is_valid():
            send = form.save()
            total,success = send.do()
            msg = '%d 封邮件正在等待发送' % (total)
            messages.success(request,msg)
            return redirect('home')

    ctx = {'form':form}
    ctx['objs'] = m.Tmail.objects.all()
    return render(request,'home.html',ctx)

def preview(request,pk):
    tmail = get_object_or_404(m.Tmail,pk=pk)
    return render(request,tmail.tpath())

htmlmail/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}html-mail{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstraped/css/bootstraped.css" type="text/css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}htmlmail/css/base.css" type="text/css" />
    {% block css %}
    {% endblock css %}
</head>
<body>
<div id="header">{% block header %}{% endblock %}</div>
{% if messages %}
<ul class="messages unstyled">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
    <button type="button" class="close" data-dismiss="alert">×</button>
    {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
<div id="container" class='container'>
    <div id="content">{% block content %}{% endblock %}</div>
</div>
<div id="footer">{% block footer %}{% endblock %}</div>
<script src="{{ STATIC_URL }}jquery/js/jquery.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}bootstraped/js/bootstraped.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}htmlmail/js/base.js" type="text/javascript"></script>
</body>
</html>

htmlmail/templates/home.html
{% extends "base.html" %}

{% block content %}
<h2>模板列表</h2>
<a target="_blank" class="pull-right" href="/admin">管理后台</a>
<ul class="unstyled">
{% for obj in objs %}
<li>
<a target="_blank" href="{% url preview obj.pk %}">{{obj.title}}</a>
</li>
{% endfor %}
</ul>
<h2>发送邮件</h2>
<form action="" method="post" class="form">
    {% csrf_token %}
    <table class="table table-bordered table-hover">
    {{form.as_table}}
    </table>
    <div class="form-actions">
    <button type="submit" class="btn btn-primary btn-large">发送</button>
    </div>
</form>
{% endblock %}

{% block css %}
<style type="text/css">
#id_mails {
    width: 98%;
}
</style>
{% endblock css %}

htmlmail/templates/mail_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}Insigma{% endblock %}</title>
	<style type="text/css">
		/* Based on The MailChimp Reset INLINE: Yes. */
		/* Client-specific Styles */
		#outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
		body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
		/* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/
		.ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		/* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
		#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
		/* End reset */

		/* Some sensible defaults for images
		Bring inline: Yes. */
		img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
		a img {border:none;}
		.image_fix {display:block;}

		/* Yahoo paragraph fix
		Bring inline: Yes. */
		p {margin: 1em 0;}

		/* Hotmail header color reset
		Bring inline: Yes. */
		h1, h2, h3, h4, h5, h6 {color: black !important;}

		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
		color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
		color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		/* Outlook 07, 10 Padding issue fix
		Bring inline: No.*/
		table td {border-collapse: collapse;}

		/* Remove spacing around Outlook 07, 10 tables
		Bring inline: Yes */
		table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

		/* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email and make sure to bring your styles inline.  Your link colors will be uniform across clients when brought inline.
		Bring inline: Yes. */
		a {color: orange;}


		/***************************************************
		****************************************************
		MOBILE TARGETING
		****************************************************
		***************************************************/
		@media only screen and (max-device-width: 480px) {
			/* Part one of controlling phone number linking for mobile. */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}

		}

		/* More Specific Targeting */

		@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
		/* You guessed it, ipad (tablets, smaller screens, etc) */
			/* repeating for the ipad */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}
		}

		@media only screen and (-webkit-min-device-pixel-ratio: 2) {
		/* Put your iPhone 4g styles in here */
		}

		/* Android targeting */
		@media only screen and (-webkit-device-pixel-ratio:.75){
		/* Put CSS for low density (ldpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1){
		/* Put CSS for medium density (mdpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1.5){
		/* Put CSS for high density (hdpi) Android layouts in here */
		}
		/* end Android targeting */

	</style>

	<!-- Targeting Windows Mobile -->
	<!--[if IEMobile 7]>
	<style type="text/css">

	</style>
	<![endif]-->

	<!-- ***********************************************
	****************************************************
	END MOBILE TARGETING
	****************************************************
	************************************************ -->

	<!--[if gte mso 9]>
		<style>
		/* Target Outlook 2007 and 2010 */
		</style>
	<![endif]-->
</head>
<body>
<!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->
<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
	<tr>
		<td valign="top">
		<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->
		<table cellpadding="0" cellspacing="0" border="0" align="center">
            {% block content %}
            {% endblock %}
		</table>
		<!-- End example table -->

		<!-- Yahoo Link color fix updated: Simply bring your link styling inline. -->
		<a href="http://iottech.com.cn" target ="_blank" title="Styling Links" style="color: orange; text-decoration: none;">insigma IOT</a>

		<!-- Gmail/Hotmail image display fix -->
		<!--img class="image_fix" src="full path to image" alt="Your alt text" title="Your title text" width="x" height="x" /-->

		<!-- Working with telephone numbers (including sms prompts).  Use the "mobile" class to style appropriately in desktop clients
		versus mobile clients. -->
		<span class="mobile_link">0571-87750290</span>

		</td>
	</tr>
</table>
<!-- End of wrapper table -->
</body>
</html>

htmlmail/templates/mail_evernote.html
{% extends "mail_base.html" %}

{% block title %}Welcome to Insigma IOT{% endblock %}

{% block content %}
<tr>
<td width="100%" bgcolor="#e6e6e6">
<table cellspacing="0" cellpadding="0" border="0" align="center" style="width: 584px;" class="table">
<tr>
<td width="584">
<p style="color: #808080; font-size: 11px; line-height: 30px; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; margin: 0; padding: 0; font-weight: normal; text-align: center;"><a target="_blank" href="http://iottech.com.cn"  style="color: #808080;" name="chrome_clipper_gmail_web"><span style="color: #808080;">浏览网页版</span></a></p>
<table cellspacing="0" cellpadding="0" border="0" style="width: 584px;">
<tr>
<td width="584" style="background-color: #7cbc48;"><a href="http://links.evernote.mkt5371.com/ctt?kn=3&ms=NjQxMDQ3OQS2&r=MzMwMzA2OTU0NzAS1&b=0&j=NzY1MzEwNTYS1&mt=1&rt=0" target="_blank" name="chrome_clipper_gmail_header" ><img width="584" height="57" border="0"  src="http://www.yinxiang.com/media/yxbj/images/email_header.png" alt="印象笔记" style="margin: 0; padding: 0; display: block;" /></a></td>
</tr>
</table>
<table cellspacing="0" cellpadding="0" border="0" style="width: 584px; -webkit-text-size-adjust: none;">
<tr>
<td width="580" style="background-color: #ffffff; background-image: url('http://evernote.com/media/img/email/interspire/background_body.gif'); background-position: 0 0; background-repeat: repeat-y; padding-left: 2px; padding-right: 2px;">
<table cellspacing="0" cellpadding="0" border="0" style="width: 580px; -webkit-text-size-adjust: none;">
<tr>
<td width="500" colspan="3" style="background-color: #ffffff; background-image: url('http://evernote.com/media/img/email/interspire/background_body-top.gif'); background-position: 0 0; background-repeat: repeat-x; padding: 20px 28px 0 28px;">
<p align="center" style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', sans-serif; font-weight: normal !important; font-size: 26px; line-height: 33px; color: #7e7d7e; margin-top: 10px; margin-left: 0; margin-bottom: 20px; margin-right: 0; padding-top: 10px; padding-bottom: 10px;">剪藏+印象笔记，决胜邮箱之巅！</p>
</td>
</tr>
<tr>
<td align="center" colspan="3" style="background-color: #ffffff; padding: 0;"><a  name="chrome_clipper_gmail_download_hero" target="_blank" href="http://links.evernote.mkt5371.com/ctt?kn=1&ms=NjQxMDQ3OQS2&r=MzMwMzA2OTU0NzAS1&b=0&j=NzY1MzEwNTYS1&mt=1&rt=0"><img  src="http://www.yinxiang.com/media/yxbj/products/images/gmail_tips.jpeg" alt="一键剪藏Gmail邮件和附件" style="max-width: 100%; height: auto;" /></a></td>
</tr>
<tr>
<td valign="top" height="170" colspan="3" style="background-color: #ffffff; padding: 10px 40px 0 50px;">
<p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; color: #7e7d7e; margin-top: 10px; margin-left: 0; margin-bottom: 14px; margin-right: 0; padding: 0;">巨慢无比的Gmail，折磨的你痛不欲生，却又无法割舍？</p>
<p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; color: #7e7d7e; margin-top: 10px; margin-left: 0; margin-bottom: 14px; margin-right: 0; padding: 0;"><a href="http://links.evernote.mkt5371.com/ctt?kn=11&ms=NjQxMDQ3OQS2&r=MzMwMzA2OTU0NzAS1&b=0&j=NzY1MzEwNTYS1&mt=1&rt=0" style="font-family: arial,Helvetica,sans-serif; font-size: 15px; color: #48b4c1; text-decoration: none;" target="_blank" name="chrome_clipper_gmail_update" ><span style="color: #48b4c1;">印象笔记&bull;剪藏Chrome版</span></a>盛大更新，一键剪藏Gmail邮件和附件！从此告别漫长等待，在印象笔记里快速看附件，轻松保存重要邮件！</p>
<p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; color: #7e7d7e; margin-top: 10px; margin-left: 0; margin-bottom: 14px; margin-right: 0; padding: 0;">还有<a target="_blank" href="http://links.evernote.mkt5371.com/ctt?kn=4&ms=NjQxMDQ3OQS2&r=MzMwMzA2OTU0NzAS1&b=0&j=NzY1MzEwNTYS1&mt=1&rt=0"  style="font-family: arial,Helvetica,sans-serif; font-size: 15px; color: #48b4c1; text-decoration: none;" name="chrome_clipper_gmail_tips"><span style="color: #48b4c1;">超级策略</span></a>，为你双手奉上，重要邮件妥妥保存，查找邮件轻轻松松！</p>
<p style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; color: #7e7d7e; margin-top: 10px; margin-left: 0; margin-bottom: 14px; margin-right: 0; padding: 0;">立即告诉你的朋友这个好消息吧！7天之内，推荐用Gmail的朋友下载印象笔记并成功注册，你和朋友就有机会免费获得一个月1G流量！(记得把你和朋友的注册邮箱地址，发邮件到<a  name="jiancang_yinxiang_com" href="mailto:jiancang@yinxiang.com" style="font-family: arial,Helvetica,sans-serif; font-size: 15px; color: #48b4c1; text-decoration: none;"><span style="color: #48b4c1;">jiancang@yinxiang.com</span></a>哦)</p>
</td>
</tr>
<tr>
<td width="195" height="20" style="background_color: #ffffff; padding: 20px 0 10px 0;"></td>
<td width="195" valign="top" height="20" align="center" style="background-color: #ffffff; padding: 20px 0 10px 0;">
{% endblock %}

htmlmail/templates/mail_hello.html
{% extends "mail_base.html" %}

{% block title %}Welcome to Insigma IOT{% endblock %}

{% block content %}
<tr>
    <td width="200" valign="top">
        Welcome to Insigma IOT
    </td>
    <td width="200" valign="top"></td>
    <td width="200" valign="top"></td>
</tr>
{% endblock %}

htmlmail/templates/ref/email_lite.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>Your Message Subject or Title</title>
	<style type="text/css">
		/* Based on The MailChimp Reset INLINE: Yes. */
		/* Client-specific Styles */
		#outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
		body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
		/* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/
		.ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		/* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */
		#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
		/* End reset */

		/* Some sensible defaults for images
		Bring inline: Yes. */
		img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
		a img {border:none;}
		.image_fix {display:block;}

		/* Yahoo paragraph fix
		Bring inline: Yes. */
		p {margin: 1em 0;}

		/* Hotmail header color reset
		Bring inline: Yes. */
		h1, h2, h3, h4, h5, h6 {color: black !important;}

		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
		color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
		color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		/* Outlook 07, 10 Padding issue fix
		Bring inline: No.*/
		table td {border-collapse: collapse;}

		/* Remove spacing around Outlook 07, 10 tables
		Bring inline: Yes */
		table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

		/* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email and make sure to bring your styles inline.  Your link colors will be uniform across clients when brought inline.
		Bring inline: Yes. */
		a {color: orange;}


		/***************************************************
		****************************************************
		MOBILE TARGETING
		****************************************************
		***************************************************/
		@media only screen and (max-device-width: 480px) {
			/* Part one of controlling phone number linking for mobile. */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}

		}

		/* More Specific Targeting */

		@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
		/* You guessed it, ipad (tablets, smaller screens, etc) */
			/* repeating for the ipad */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}
		}

		@media only screen and (-webkit-min-device-pixel-ratio: 2) {
		/* Put your iPhone 4g styles in here */
		}

		/* Android targeting */
		@media only screen and (-webkit-device-pixel-ratio:.75){
		/* Put CSS for low density (ldpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1){
		/* Put CSS for medium density (mdpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1.5){
		/* Put CSS for high density (hdpi) Android layouts in here */
		}
		/* end Android targeting */

	</style>

	<!-- Targeting Windows Mobile -->
	<!--[if IEMobile 7]>
	<style type="text/css">

	</style>
	<![endif]-->

	<!-- ***********************************************
	****************************************************
	END MOBILE TARGETING
	****************************************************
	************************************************ -->

	<!--[if gte mso 9]>
		<style>
		/* Target Outlook 2007 and 2010 */
		</style>
	<![endif]-->
</head>
<body>
<!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->
<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
	<tr>
		<td valign="top">
		<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->
		<table cellpadding="0" cellspacing="0" border="0" align="center">
			<tr>
				<td width="200" valign="top"></td>
				<td width="200" valign="top"></td>
				<td width="200" valign="top"></td>
			</tr>
		</table>
		<!-- End example table -->

		<!-- Yahoo Link color fix updated: Simply bring your link styling inline. -->
		<a href="http://htmlemailboilerplate.com" target ="_blank" title="Styling Links" style="color: orange; text-decoration: none;">Coloring Links appropriately</a>

		<!-- Gmail/Hotmail image display fix -->
		<img class="image_fix" src="full path to image" alt="Your alt text" title="Your title text" width="x" height="x" />

		<!-- Working with telephone numbers (including sms prompts).  Use the "mobile" class to style appropriately in desktop clients
		versus mobile clients. -->
		<span class="mobile_link">123-456-7890</span>

		</td>
	</tr>
</table>
<!-- End of wrapper table -->
</body>
</html>